version: '2.1'

services:
  mysql:
    build: ./mysql
    container_name: mysql_server
    ports:
      - "3306:3306"
    networks:
      - backend

  web:
    build: ./web
    container_name: web_server
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend: