version: '2.1'

services:
  mysql:
    container_name: mysql_server
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "daw"
    ports:
      - "33060:3306"
    networks:
      - backend

  api:
    container_name: api_server
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend: