version: '2.1'

services:
  mysql:
    build: ./mysql
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "daw"
    ports:
      - "3306:3306"
    networks:
      - backend

  docker-wait:
    build: ./docker-wait
    container_name: docker-wait
    depends_on:
      - mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "sh /wait.sh"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api_server
    ports:
      - "8080:8080"
    depends_on:
      docker-wait:
        condition: service_healthy
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend: